### PR TITLE
Updated ROS apt key for kinetic. Cf. #18

### PR DESCRIPTION
**Pull request by blumenthal**
Hi @DharminB ,
I could not finish the test in the docker, since it did not have lsb_release pre-installed. This is required to set up correct apt sources...

Could you please test it again?

### CODE REVIEW

**Comment by DharminB** [comment]
I found the cause of this problem [here](https://stackoverflow.com/a/43127088/10460994). I also think the fix is as simple as `source /etc/os-release; echo $UBUNUT_CODENAME`. I tested this command it works as expected. Should I change the `install_software` script with this fix?

**Comment by blumenthal** [comment]
That would be nice ;-)

**Comment by DharminB** [comment]
@blumenthal Could you please accept #20 ? I had to create a PR since I do not have push access to this repo...

**Comment by blumenthal** [comment]
New apt key was nested on a fresh installation

**Pull request merged**
